theme: jekyll-theme-merlot
title: Welcome to Samme Janderson's homepage
description: Feel free to bookmark this to keep an eye in my project updates


<iframe src="https://giphy.com/embed/IPbS5R4fSUl5S" width="480" height="266" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/IPbS5R4fSUl5S">via GIPHY</a></p>
